name: scrape latest data

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: check out this repo
        uses: actions/checkout@v2
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/puppeteer
          key: node_modules-${{ hashfiles('package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: fetch latest data
        run: npm start
      - name: commit and push if it changed
        run: ./update.sh
