name: scrape latest data

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: self-hosted
    steps:
      - name: check out this repo
        uses: actions/checkout@v2
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: node_modules-${{ hashfiles('yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - name: fetch latest data
        run: yarn start
      - name: commit and push if it changed
        run: ./update.sh
