name: scrape latest data

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: check out this repo
        uses: actions/checkout@v2
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/puppeteer
          key: node_modules-${{ hashfiles('yarn.lock') }}
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: fetch latest data
        run: yarn start
      - name: commit and push if it changed
        run: |-
          git config user.name "automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          results=$(cat results.json | wc -l)
          if [ "${results}" -ne "0" ]; then curl -d "Available appointments found (${results})! Book fast!" ntfy.sh/anmeldung || exit 0; fi
          rm -f README.md; echo "# available appointments\n" > README.md; cat results.json >> README.md
          git commit -m "latest data: ${timestamp}, slots: ${results}" || exit 0
          git push
