name: scrape latest data

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: check out this repo
        uses: actions/checkout@v2
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/puppeteer
          key: node_modules-${{ hashfiles('yarn.lock') }}
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: fetch latest data
        run: yarn start > results.json
      - name: commit and push if it changed
        run: |-
          git config user.name "automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "latest data: ${timestamp}" || exit 0
          git push
